### PR TITLE
Implemented myIncludes, myIndexOf and myPush funcs

### PR DESCRIPTION
**Pull request by George-Sucuzhanay**
Developed our own version of the following JS methods

- myIncludes()
- myIndexOf()
- myPush()

Viewed on george.js

### CODE REVIEW

**Comment by Rahatk1** [comment]
Looks great

**Comment by George-Sucuzhanay** [comment]
working on testing methods on george.html 👍

**Comment by George-Sucuzhanay** [comment]
ready for review thanks! 🫡

**Comment by Kazi27** [comment]
Looks good to me!

**Pull request merged**
